title: Lisa Qiu # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A third-year Marketing student at Queen's University passionate about digital marketing and graphic design 
  <br><br>
  <a href="https://www.linkedin.com/in/lisa-qiu-930102148/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
